import { readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { format, resolveConfig } from "prettier";

const here = path.dirname(fileURLToPath(import.meta.url));
const iconsDirectory = path.join(here, "../assets/icons");
const outputPath = path.join(here, "../components/atoms/svg-icon/icon-names.ts");
const extension = ".svg";

const names = readdirSync(iconsDirectory)
  .filter((file) => file.endsWith(extension))
  .sort()
  .map((file) => file.slice(0, -extension.length));

const source = [
  "// Generated by `npm run generate-icon-types` from src/assets/icons. Do not edit by hand.",
  `export const iconNames = ${JSON.stringify(names)} as const;`,
  ""
].join("\n");

const options = await resolveConfig(outputPath);
writeFileSync(outputPath, await format(source, { ...options, filepath: outputPath }));
console.log(`Wrote ${names.length} icon names to ${path.relative(process.cwd(), outputPath)}`);
