name: Deploy prod

# Trigger the workflow only for protected tags matching the specified pattern.
on:
  push:
    tags:
      - v*.*.*

env:
  BUCKET_NAME: storybook-nolus
  CLOUDFRONT_ID: E213OV9IDTDHKX
  AWS_REGION: eu-west-1
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    name: Build static files
    runs-on: ubuntu-22.04 # Use updated Ubuntu version for better compatibility
    container: node:20.9.0 # Node.js container stays the same

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          npm install
          npm run build-storybook

      - name: Archive src
        uses: actions/upload-artifact@v3
        with:
          name: src
          path: dist/

  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-22.04 # Updated runner for compatibility
    environment: production
    needs: build

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download src
        uses: actions/download-artifact@v3
        with:
          name: src
          path: dist/

      - name: Sync bucket
        run: |
          aws s3 sync dist/ s3://${BUCKET_NAME}

  invalidate-cache:
    name: Invalidate cache
    runs-on: ubuntu-22.04 # Updated runner for compatibility
    environment: production
    needs: deploy

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_ID} --paths "/*" --output table
          echo "Cache invalidation usually takes a couple of minutes"
